name: Add new issue or pull request to sl1 project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-to-project:
    name: Add issue or pull request to project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/openMSL/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

