name: Credibility Assessment Level 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_model:
    name: Build Model
    uses: openMSL/sl-1-0-sensor-model-repository-template/.github/workflows/build.yml@minimal_sensor_model

  cpp-linter:
    name: C++ Linter
    uses: openMSL/sl-1-0-sensor-model-repository-template/.github/workflows/cpp-linter.yml@minimal_sensor_model
