name: Credibility Assessment Level 1

on:
  workflow_call:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    name: Clear Model Cache
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
            }
            github.rest.actions.deleteActionsCacheByKey({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: "${{ runner.os }}-model-fmu",
            })
            console.log("Clear completed")

  build_model:
    name: Build Model
    uses: ./.github/workflows/build.yml

  fmu-artifact:
    needs: build_model
    name: FMU Artifact
    uses: ./.github/workflows/fmu_artifact.yml

  fmu-checker:
    needs: build_model
    name: FMU Compliance Checker
    uses: ./.github/workflows/fmu_checker.yml

  cpp-linter:
    name: C++ Linter
    uses: ./.github/workflows/cpp-linter.yml

  markdown-linter:
    name: Markdown Linter
    uses: ./.github/workflows/markdown.yml

  srmd-validator:
    name: SRMD Validator
    uses: ./.github/workflows/srmd-validator.yml

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yml