name: Credibility Assessment Level 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_model:
    name: Build Model
    uses: openMSL/sl-1-0-sensor-model-repository-template/.github/workflows/build.yml@main

  build_tracefile_player:
    name: Build Tracefile Player FMU
    runs-on: ubuntu-latest

    steps:
    - name: Cache Dependencies
      id: cache-depends
      uses: actions/cache@v3
      with:
        path: protobuf-21.12
        key: ${{ runner.os }}-v1-depends

    - name: Download ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

    - name: Build ProtoBuf
      if: steps.cache-depends.outputs.cache-hit != 'true'
      working-directory: protobuf-21.12
      run: ./configure DIST_LANG=cpp --disable-shared CXXFLAGS="-fPIC" && make

    - name: Install ProtoBuf
      working-directory: protobuf-21.12
      run: sudo make install && sudo ldconfig

    - name: Get Tracefile Player
      run: git clone https://gitlab.com/persival-open-source/open-simulation-interface/osi-trace-file-player.git

    - name: Prepare C++ Build
      working-directory: osi-trace-file-player
      run: git submodule update --init && mkdir build

    - name: Configure CMake
      working-directory: osi-trace-file-player/build
      run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

    - name: Build C++
      working-directory: osi-trace-file-player/build
      run: cmake --build .
      
    - name: Create FMU Directory
      working-directory: osi-trace-file-player/build
      run: mkdir /tmp/tracefile_fmu

    - name: Copy Tracefile FMU
      working-directory: osi-trace-file-player/build
      run: cp src/OSMPTraceFilePlayer.fmu /tmp/tracefile_fmu/OSMPTraceFilePlayer.fmu

    - name: Cache Tracefile FMU
      id: cache-tracefile-fmu
      uses: actions/cache@v3
      with:
        path: /tmp/tracefile_fmu
        key: ${{ runner.os }}-tracefile-fmu

  build_osi_field_checker_fmu:
    name: Build OSI Field Checker FMU
    runs-on: ubuntu-latest

    steps:
      - name: Cache Dependencies
        id: cache-depends
        uses: actions/cache@v3
        with:
          path: protobuf-21.12
          key: ${{ runner.os }}-v1-depends

      - name: Download ProtoBuf
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz && tar xzvf protobuf-all-21.12.tar.gz

      - name: Build ProtoBuf
        if: steps.cache-depends.outputs.cache-hit != 'true'
        working-directory: protobuf-21.12
        run: ./configure DIST_LANG=cpp --disable-shared CXXFLAGS="-fPIC" && make

      - name: Install ProtoBuf
        working-directory: protobuf-21.12
        run: sudo make install && sudo ldconfig

      - name: Clone OpenMSL Sensor Model Testing
        run: git clone https://github.com/openMSL/sl-1-5-sensor-model-testing.git

      - name: Prepare C++ Build
        working-directory: sl-1-5-sensor-model-testing
        run: git submodule update --init && mkdir build

      - name: Configure CMake
        working-directory: sl-1-5-sensor-model-testing/build
        run: cmake -DCMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install ..

      - name: Build C++
        working-directory: sl-1-5-sensor-model-testing/build
        run: cmake --build .

      - name: Create FMU Directory
        working-directory: sl-1-5-sensor-model-testing/build
        run: mkdir /tmp/osi-field-checker

      - name: Copy OSI Field Checker FMU
        working-directory: sl-1-5-sensor-model-testing/build
        run: cp OSIFieldChecker.fmu /tmp/osi-field-checker/OSIFieldChecker.fmu

      - name: Cache OSI Field Checker FMU
        id: cache-osi-field-checker
        uses: actions/cache@v3
        with:
          path: /tmp/osi-field-checker
          key: ${{ runner.os }}-osi-field-checker

  build_openmcx:
    name: Build OSI Field Checker FMU
    runs-on: ubuntu-latest

    steps:
      - name: Cache OpenMCx
        id: cache-openmcx
        uses: actions/cache@v3
        with:
          path: openmcx
          key: ${{ runner.os }}-openmcx

      - name: Install dependencies
        run: sudo apt install -y libxml2-dev zlib1g-dev libzip-dev

      - name: Get OpenMCx
        if: steps.cache-openmcx.outputs.cache-hit != 'true'
        run: git clone https://github.com/eclipse/openmcx.git

      - name: Build OpenMCx
        if: steps.cache-openmcx.outputs.cache-hit != 'true'
        working-directory: openmcx
        run: ./build.sh

  run_osi_field_check:
    needs: [build_model, build_tracefile_player, build_openmcx, build_osi_field_checker_fmu]
    name: Run Model FMU
    uses: openMSL/sl-1-0-sensor-model-repository-template/test/integration/001_output_osi_fields/test_action.yml@25-move-pipeline-files-to-test-folder



