name: Lint

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download schema
      run: git clone https://github.com/PMSFIT/SSPTraceability.git
    - name: Validate SRMD
      uses: cardinalby/schema-validator-action@v1
      with:
        file: '*.srmd'
        schema: './SSPTraceability/SRMD.xsd'
