name: Lint

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download schema
      run: git clone git@github.com:PMSFIT/SSPTraceability.git
    - name: Lint info.xml
      uses: korelstar/xmllint-problem-matcher@v1
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./sl-1-0-sensor-model-repository-template.srmd
        xml-schema-file: ./SSPTraceability/SRMD.xsd
